# Generated by Django 3.2.19 on 2024-09-21 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 8, 23, 40, 86047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 8, 23, 40, 87006, tzinfo=utc)),
        ),
    ]
