# Generated by Django 3.2.19 on 2024-09-21 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240921_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 12, 19, 2, 512104, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 12, 19, 2, 513015, tzinfo=utc)),
        ),
    ]
