# Generated by Django 3.2.19 on 2024-09-30 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240929_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 9, 19, 22, 21, 699072)),
        ),
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 9, 19, 22, 21, 700206)),
        ),
        migrations.AlterField(
            model_name='card',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('Critical', 'Critical')], default='MEDIUM', max_length=10),
        ),
    ]
