# Generated by Django 3.2.19 on 2024-10-11 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20241005_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='theuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 16, 8, 32, 781366)),
        ),
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 16, 8, 32, 789521)),
        ),
    ]
