# Generated by Django 3.2.19 on 2024-10-12 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20241012_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 21, 17, 57, 2, 828576)),
        ),
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 21, 17, 57, 2, 829511)),
        ),
    ]
